services:
  # 服务名
  metar-provider:
    # 使用的镜像
    image: halfnothing/metar-provider:latest
    # 容器名称
    container_name: metar-provider
    # 端口映射
    # 宿主机端口:容器端口
    networks:
      - main
    ports:
      - "8080:8080"
      - "8081:8081"
    # 挂载卷列表
    volumes:
      - ./logs:/metar-provider/logs
      - ./config.yaml:/metar-provider/config.yaml
    # 重启模式
    restart: always

networks:
  main:
    driver: bridge